### ISSUE TITLE
Add the Intercon T Iron GM contest info to the larp writing contests page

### ISSUE THREAD

**Issue by valleyviolet** [neinteractiveliterature/interactiveliterature.org#14]
The following was the announcement on slack about the winners of the contest (and I think it includes all the other teams as well):

> I am very pleased to announce the teams in the Iron GM contest, who all wrote and ran close-scoring games with the genre of Monster Stories, the theme of Immortality, the ingredient of Silence, and the prop of a Lantern. Participating but not placing:
> Geese In Our Thyme (Jacqueline Bryk, Ben Walker, Justin Buckley) with "Cryptid Connection" : a fun take on Werewolf-style hidden role games, with characters telling stories that reveal enough, but not too much.
> The Tenth Muse (Josh Sheena, Meghan Coppock) with "The Horror of Wadi Alwasi" : a tightly written, tense game of a village wrapped in a dangerous secret that could bring about their survival...or their doom
> In 3rd Place:
> LIMINALITY OCTOPUS (Xavid Pretzer, Jakob Weisblat, Edwin Karat) with "In the Hall of the Beast" : a mechanically ambitious, evocatively described game of secrets, gambling, and the Devil Themself
>  In 2nd Place:
>  Hanging Lanturn (Benji Michalek, Jeff Steele, Natasha Borders) with "Respawn" : a small, sweet, and close game on the other side of dungeon adventuring, where players are super-charming monsters who love each other
>  And finally, in 1st Place:
>  Witching Hour (Michael Von Korff, Kiara Vincent, Elisabeth Cohen, Sarah Judd) with "Into the Abyss": a game where there are monsters, some from beyond time, some that are human, with wonderful replayability and evocative mechanics
>  Thank you so much to our writers, readers, and players; this contest would not exist without you!

**Comment by diewald** [comment]
Done locally, with changes pushed to repo. Will update to website when I can.

**Comment by diewald** [comment]
Uploaded and visible.
