### ISSUE TITLE
Point interconlarp.org to Intercon T

### ISSUE THREAD

**Issue by diewald** [neinteractiveliterature/interactiveliterature.org#2]
The short-term fix to the navigation issues on interactiveliterature.org is to:

- Change interconlarp.org to point to T instead of S
- Create navigation artwork for Intercon T as a GIF
- Install the T artwork as images/nextInterconLogo.gif in the interactiveliterature.org tree

This will work with the current structure of interactiveliterature.org until Eva and I figure out how to simplify the generation of the navigation links.

**Comment by nbudin** [comment]
I've updated interconlarp.org's redirection rules in AWS.  It should now be pointing at t.interconlarp.org.

**Comment by diewald** [comment]
I've put a temporary T image in place.

**Comment by diewald** [comment]
Fixed long ago.
