### ISSUE TITLE
Update the NEIL Community Meetings page

### ISSUE THREAD

**Issue by valleyviolet** [neinteractiveliterature/interactiveliterature.org#6]
Update https://github.com/neinteractiveliterature/interactiveliterature.org/blob/master/NEIL/communityMeetings.html

Right now it lists a rather antique meeting as the next one and the google calendar link doesn't work anymore (unless NEIL is still using Google Calendar events to hold agenda info, we should remove the link entirely).

**Comment by diewald** [comment]
The page now holds the Intercon calendar, so meetings should be visible, as well as other important event information.
