### ISSUE TITLE
Add the Intercon S Iron GM contest info to the larp writing contests page

### ISSUE THREAD

**Issue by valleyviolet** [neinteractiveliterature/interactiveliterature.org#7]
Get info on the teams, team members, games, and prizes for the Intercon S Iron GM contest and add it to the larp writing contests page ( https://github.com/neinteractiveliterature/interactiveliterature.org/blob/master/NEIL/larpWritingContests.html ).

**Comment by valleyviolet** [comment]
Kim provided info on some of the teams and the prizes:

> This year's ingredients were: Genre: Magical Realism, Theme: Coming of Age, Element: A Distress Call and the prop: A 10" flat table top mirror
> 
> The results of the Intercon S Iron GM Competition were that:
> 
> - 8 teams completed the writing portion of the competition this year. They did fantastic jobs writing complete larps for between 5 to 12 players that run for 2 hours each.
> 
> - 7 readers read, and scored the anonymized games
> 
> - 7 teams ran their games at Intercon S
> 
> - The 8th team, "Gap Year" did not run and therefore was not eligible to compete, but we are looking forward to hopefully seeing their game run somewhere soon.
> 
> - 50 player slots were run at Iron GM game; 3 games ran with 8 players at 10:00 am, 3 games ran with 7 players at 12:30 pm, and 1 game ran with 6 players at 3:00 pm
> 
> Game scores were made up of a combination of reader and player feedback scores.
> 
> 
> 
> And now, patient readers, the competition results:
> 1st prize winner ($250), "The Leonids" by Paranoid & Crotchety, Liliya Benderskaya & Tory Root
> 
> 2nd prize winner ($150),"Self Reflections" by The Witching Hour, Sarah Judd, Kiara Vincent, Michael Von Korff, Elisabeth Cohen
> 
> 3rd prize winner ($100), "Nightingale" by Hanging Lantern, Natasha Borders, Benji Michalek, Jeff Steele

**Comment by diewald** [comment]
I have the edits in place for this, locally. I'm working with Nat to reconnect to the new AWS space.

**Comment by diewald** [comment]
Note that the winners are already uploaded and visible.
