### ISSUE TITLE
See if Kim Sward has an email to list on the NEIL Board page

### ISSUE THREAD

**Issue by valleyviolet** [neinteractiveliterature/interactiveliterature.org#8]
Right now the page for the NEIL Board ( https://github.com/neinteractiveliterature/interactiveliterature.org/blob/master/NEIL/neilBoard.html ) page lists Kim Sward's email as "TBD". Find out if there's an email Kim wants there. If so, put it there; if not, take the TBD off.

**Comment by dkapell** [comment]
Please update that page with the current board and replace the email addresses with the below:
Dave Kapell - President - Expires 2020 - dave.kapell@interactiveliterature.org
John Cooke - Expires 2020 - john.cooke@interactiveliterature.org
Jen Benfield - Expires 2020 - jenn.benfield@interactiveliterature.org
Adina Schreiber - Expires 2020 - adina.schreiber@interactiveliterature.org
Kim Sward - Expires 2021 - kim.sward@interactiveliterature.org
Jen Eastman-Lawrence - Expires 2021 - jen.eastman-lawrence@interactiveliterature.org
Rachel Nations - Expires 2021 - rachel.nations@interactiveliterature.org
Plus
Chad Bergeron (Treasurer) - 2020 - treasurer@interactiveliterature.org
Jaelen Hartwin (Conchair, Intercon T) - 2020- conchair@t.interconlarp.org
Cameron (NELCO Coordinator) - 2020 - nelco@interactiveliterature.org

**Comment by diewald** [comment]
Done, with the 2020 information and addresses.
