### ISSUE TITLE
Add NEIL History from 2017-present

### ISSUE THREAD

**Issue by valleyviolet** [neinteractiveliterature/interactiveliterature.org#9]
Right now the NEIL History page ( https://github.com/neinteractiveliterature/interactiveliterature.org/blob/master/NEIL/neilHistory.html ) includes information on board members and brief meeting summaries describing changes to the board through 2017. We should add similar info for 2017-now.

**Comment by diewald** [comment]
Someone may have done this, only to have the changes overwritten. Those changes were *never* checked into the repo.

**Comment by diewald** [comment]
This has been superseded by #17. Most of the work has been done -- there are only a few specific questions remaining.
